/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpleadoRouteImport } from './routes/empleado'
import { Route as EmpleosRouteImport } from './routes/empleos'
import { Route as EmpresarioRouteImport } from './routes/empresario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadoRoute = EmpleadoRouteImport.update({
  id: '/empleado',
  path: '/empleado',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleosRoute = EmpleosRouteImport.update({
  id: '/empleos',
  path: '/empleos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresarioRoute = EmpresarioRouteImport.update({
  id: '/empresario',
  path: '/empresario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empleado': typeof EmpleadoRoute
  '/empleos': typeof EmpleosRoute
  '/empresario': typeof EmpresarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empleado': typeof EmpleadoRoute
  '/empleos': typeof EmpleosRoute
  '/empresario': typeof EmpresarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empleado': typeof EmpleadoRoute
  '/empleos': typeof EmpleosRoute
  '/empresario': typeof EmpresarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/empleado' | '/empleos' | '/empresario'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/empleado' | '/empleos' | '/empresario'
  id: '__root__' | '/' | '/empleado' | '/empleos' | '/empresario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpleadoRoute: typeof EmpleadoRoute
  EmpleosRoute: typeof EmpleosRoute
  EmpresarioRoute: typeof EmpresarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleado': {
      id: '/empleado'
      path: '/empleado'
      fullPath: '/empleado'
      preLoaderRoute: typeof EmpleadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleos': {
      id: '/empleos'
      path: '/empleos'
      fullPath: '/empleos'
      preLoaderRoute: typeof EmpleosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresario': {
      id: '/empresario'
      path: '/empresario'
      fullPath: '/empresario'
      preLoaderRoute: typeof EmpresarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpleadoRoute: EmpleadoRoute,
  EmpleosRoute: EmpleosRoute,
  EmpresarioRoute: EmpresarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
